const allLocations = [
  {
    name: "E1",
    lat: 48.143521,
    lng: 11.587734,
    skill: "advanced",
    city: "Munich",
    country: "Germany",
    technology: "river",
    open: "all year",
    website: "",
    cost: "free",
  },
  {
    name: "E2",
    lat: 48.14794,
    lng: 11.592334,
    skill: "intermediate",
    city: "Munich",
    country: "Germany",
    technology: "river",
    open: "all year",
    website: "",
    cost: "free",
  },
  {
    name: "Floßländle",
    lat: 48.090327,
    lng: 11.545331,
    skill: "beginner",
    city: "Munich",
    country: "Germany",
    technology: "river",
    open: "all year",
    website: "",
    cost: "free",
  },
  {
    name: "Jochen Schweizer Arena",
    lat: 48.042128,
    lng: 11.653578,
    skill: "all",
    city: "Munich",
    country: "Germany",
    technology: "citywave",
    open: "all year",
    website: "",
    cost: "yes",
  },
  {
    name: "Cunovo Wave",
    lat: 48.02856,
    lng: 17.231844,
    skill: "all",
    city: "Bratislava",
    country: "Slovenia",
    technology: "river",
    open: "",
    website: "https://www.divokavoda.sk/aktivity-sport/surfing/",
    cost: "yes",
  },
  {
    name: "Almkanal",
    lat: 47.762005,
    lng: 13.038073,
    skill: "all",
    city: "Salzburg",
    country: "Austria",
    technology: "river",
    open: "",
    website: "https://www.almkanal.at/surfen_almkanal_welle.html",
    cost: "free",
  },
  {
    name: "Riverwave Thun - Scherzligschleuse",
    lat: 46.756487,
    lng: 7.632305,
    skill: "beginner",
    city: "Bern",
    country: "Switzerland",
    technology: "river",
    open: "",
    website: "https://www.flusssurfen.ch/die-spots/scherzligen",
    cost: "free",
  },
  {
    name: "Riverwave Thun - Mühleschleuse",
    lat: 46.757975,
    lng: 7.629871,
    skill: "advanced",
    city: "Bern",
    country: "Switzerland",
    technology: "river",
    open: "",
    website: "https://www.flusssurfen.ch/die-spots/muehleplatz",
    cost: "free",
  },
  {
    name: "Wellenwerk",
    lat: 52.53267,
    lng: 13.493641,
    skill: "all",
    city: "Berlin",
    country: "Germany",
    technology: "citywave",
    open: "all year",
    website: "https://wellenwerk-berlin.de/en/",
    cost: "yes",
  },
  {
    name: "Citywave Madrid",
    lat: 40.338881,
    lng: -3.848156,
    skill: "all",
    city: "Madrid",
    country: "Spain",
    technology: "citywave",
    open: "",
    website: "https://citywavemadrid.com/",
    cost: "yes",
  },
  {
    name: "Wave Island",
    lat: 44.020907,
    lng: 4.965541,
    skill: "all",
    city: "Monteux",
    country: "France",
    technology: "citywave",
    open: "temp closed - reopen spring 21",
    website: "https://www.waveisland.fr/",
    cost: "yes",
  },
  {
    name: "OANA: Citywave",
    lat: 47.092809,
    lng: 8.357266,
    skill: "all",
    city: "Luzern",
    country: "Switzerland",
    technology: "citywave",
    open: "",
    website: "https://oana.surf/citywave-surf/",
    cost: "yes",
  },
  {
    name: "Haselwelle",
    lat: 52.275068,
    lng: 8.046988,
    skill: "all",
    city: "Osnabrück",
    country: "Germany",
    technology: "citywave",
    open: "all year",
    website: "",
    cost: "yes",
  },
  {
    name: "Citywave AT",
    lat: 48.103336,
    lng: 16.31776,
    skill: "all",
    city: "Vienna",
    country: "Austria",
    technology: "citywave",
    open: "",
    website: "https://www.city-wave.at/",
    cost: "yes",
  },
  {
    name: "Urbansurf Zurich",
    lat: 47.384872,
    lng: 8.519877,
    skill: "all",
    city: "Zurich",
    country: "Switzerland",
    technology: "citywave",
    open: "",
    website: "https://urbansurf.ch/de/",
    cost: "yes",
  },
  {
    name: "The Glassy House",
    lat: 46.697375,
    lng: -1.912721,
    skill: "all",
    city: "Saint-Gilles-Croix-de-Vie",
    country: "France",
    technology: "citywave",
    open: "",
    website: "https://www.theglassyhouse.com/fr/",
    cost: "yes",
  },
  {
    name: "Surf Snowdonia",
    lat: 53.189474,
    lng: -3.839849,
    skill: "all",
    city: "Wales",
    country: "United Kingdom",
    technology: "wave pool",
    open: "all year",
    website: "https://www.adventureparcsnowdonia.com/",
    cost: "",
  },
  {
    name: "Wakeparadise Milan",
    lat: 45.453911,
    lng: 9.291053,
    skill: "all",
    city: "Milan",
    country: "Italy",
    technology: "Unit Surf Pool",
    open: "all year",
    website: "https://www.wakeparadise.it/",
    cost: "",
  },
  {
    name: "Langenfeld",
    lat: 51.113082,
    lng: 6.913147,
    skill: "all",
    city: "Langenfeld",
    country: "Germany",
    technology: "Unit Surf Pool",
    open: "March-December",
    website: "https://www.surf-langenfeld.de/home-en.html",
    cost: "",
  },
  {
    name: "The Wave",
    lat: 51.545072,
    lng: -2.605434,
    skill: "all",
    city: "Bristol",
    country: "United Kingdom",
    technology: "wave pool",
    open: "all year",
    website: "https://www.theriverwave.com/",
    cost: "",
  },
  {
    name: "Lakeside Surf: Citywave",
    lat: 47.833868,
    lng: -120.035362,
    skill: "all",
    city: "Chelan, WA",
    country: "USA",
    technology: "citywave",
    open: "summer",
    website: "https://www.lakesidesurf.com/",
    cost: "",
  },
  {
    name: "Skookumchuck",
    lat: 49.766255,
    lng: -123.937275,
    skill: "advanced",
    city: "Egmont, BC",
    country: "Canada",
    technology: "river",
    open: "",
    website: "",
    cost: "",
  },
  {
    name: "Pipeline",
    lat: 46.255657,
    lng: -115.399513,
    skill: "advanced",
    city: "Lowell, ID",
    country: "USA",
    technology: "river",
    open: "summer",
    website: "",
    cost: "",
  },
  {
    name: "Lunch Counter",
    lat: 43.195093,
    lng: -110.914991,
    skill: "advanced",
    city: "Alpine / Jackson Hole, Wyoming",
    country: "USA",
    technology: "river",
    open: "summer",
    website: "",
    cost: "",
  },
  {
    name: "Boise River Park",
    lat: 43.62683,
    lng: -116.234363,
    skill: "all",
    city: "Boise, Idaho",
    country: "USA",
    technology: "river",
    open: "spring-fall",
    website: "https://www.boisewhitewaterpark.com/welcome",
    cost: "",
  },
]
export default allLocations
